### ISSUE TITLE
All HDT files from LOD Laundromat (and more)

### ISSUE THREAD

**Issue by firmao** [LOD-Laundromat/LOD-Laundromat#7]
Hi,
How can I download all HDT files from LOD Laundromat (if you have more, I appreciate more).
Is there some big huge compressed file or something like this?

Cheers,
Andre Valdestilhas

**Comment by akuckartz** [comment]
See: http://lod-a-lot.lod.labs.vu.nl/

Huge files:
http://lod-a-lot.lod.labs.vu.nl/data/LOD_a_lot_v1.hdt
http://lod-a-lot.lod.labs.vu.nl/data/LOD_a_lot_v1.hdt.index.v1-1

**Comment by firmao** [comment]
Hi,
Thanks a lot, I'm really motivated to use those HDT files, but firstly I have some questions:

- What is the difference between the files?
- With those huge files, how to know which Dataset the data comes from, I mean the provenance of the data, where the triple comes from?
- I have no results when I query those huge files about the URI "http://dbpedia.org/resource/Leipzig" on the other hand I have results when I query the file http://gaia.infor.uva.es/hdt/dbpedia2015.hdt.gz.
why?

Cheers,
André Valdestilhas

**Comment by wouterbeek** [comment]
@firmao When I perform the query `dbr:Leipzig ?p ?o` over LOD-a-lot I get 9,208 triples.  Are you seeing any error messages?

The notion of context is problematic since HDT does not have support for graphs.

**Comment by firmao** [comment]
Another question:
HDT jena NoClassDefFoundError DatasetGraphMaker
My code:
```
private static int getCountTriples(File dataset) {
		int ret = 0;
		HDT hdt;
		try {
			hdt = HDTManager.mapHDT(dataset.getAbsolutePath(), null);
			HDTGraph graph = new HDTGraph(hdt);
			Model model = new ModelCom(graph);
			String sparql = "Select (count(?s) as ?c) where {?s ?p ?o}";
			
                     Query query = QueryFactory.create(sparql);
		    QueryExecution qe = QueryExecutionFactory.create(query, model);
		    ResultSet results = qe.execSelect();

		   if(results.hasNext()){
	               QuerySolution thisRow = results.next();
	               Literal rLiteral = ((Literal) thisRow.get("c"));
	               ret = rLiteral.getInt();
	           }
		 qe.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return ret;
	}
```

The error occurs when executes

`qe.execSelect();`

Error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/jena/sparql/core/DatasetGraphMaker
	at org.rdfhdt.hdtjena.solver.OptimizedCount.getPlan(OptimizedCount.java:137)
	at org.rdfhdt.hdtjena.solver.HDTQueryEngine.createPlan(HDTQueryEngine.java:36)
	at org.apache.jena.sparql.engine.QueryEngineBase.getPlan(QueryEngineBase.java:87)
	at org.rdfhdt.hdtjena.solver.HDTQueryEngine$HDTQueryEngineFactory.create(HDTQueryEngine.java:73)
	at org.apache.jena.sparql.engine.QueryExecutionBase.getPlan(QueryExecutionBase.java:524)
	at org.apache.jena.sparql.engine.QueryExecutionBase.startQueryIterator(QueryExecutionBase.java:472)
	at org.apache.jena.sparql.engine.QueryExecutionBase.execResultSet(QueryExecutionBase.java:511)
	at org.apache.jena.sparql.engine.QueryExecutionBase.execSelect(QueryExecutionBase.java:172)
	at HDTQueryMan.sparql(HDTQueryMan.java:88)
	at HDTQueryMan.getCountTriples(HDTQueryMan.java:163)
	at HDTQueryMan.printDatasets(HDTQueryMan.java:142)
	at HDTQueryMan.main(HDTQueryMan.java:197)
Caused by: java.lang.ClassNotFoundException: org.apache.jena.sparql.core.DatasetGraphMaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
```
Another query, such as

`Select (count(?s) as ?c) where {?s ?p ?o . filter(isLiteral(?o)) }`

works fine.

Can you help?

**Comment by wouterbeek** [comment]
Sorry, I have almost no knowledge of Jena.

**Comment by firmao** [comment]
To simplify:
I just need all HDT files from http://lodlaundromat.org/wardrobe/.
Only two columns of that table: ( "URL" and "HDT file" ).

Is it possible to obtain via SPARQL or something similar?
Why I'm doing this: To build a (huge) index where given a URI will be possible to know which dataset this URI was defined.
I'm also writing a paper, let me know if you wanna participate.

can you help me?

Cheers,
André Valdestilhas

**Comment by wouterbeek** [comment]
@firmao I've contacted you off-list.
